name: shopease
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  flutter_svg: ^2.0.9
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  flutter_typeahead: ^5.2.0
  http: ^1.1.0
  uuid: ^4.2.1
  path_provider: ^2.1.2
  path: ^1.8.3
  image_picker: ^1.0.7
  shared_preferences: ^2.5.3
  camera: ^0.10.5+9
  cupertino_icons: ^1.0.6
  dio: ^5.8.0+1
  speech_to_text: ^7.0.0
  permission_handler: ^11.4.0
  mobile_scanner: ^6.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
